version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./workspace:/app/workspace # Persist the agent's memory
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - redis

  worker:
    build: .
    volumes:
      - ./workspace:/app/workspace # Worker needs access to memory too
    command: celery -A tasks.celery worker --loglevel=info
    depends_on:
      - redis

volumes:
  workspace_data: